version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo-web
    ports:
      - "27017:27017"
    volumes:
      - mongo-web:/data/db
    networks:
      - web

volumes:
  mongo-web:

networks:
  web: